sudo: false
language: node_js
node_js:
  - "7"
cache: 
  yarn: true
  directories:
    - node_modules
before_script:
  - travis_retry npm install
script:
  - travis_retry npm run test
  - travis_retry npm run build