sudo: false
language: node_js
node_js:
  - "7"
cache: 
  yarn: true
  directories:
    - node_modules
before_script:
  - travis_retry yarn
script:
  - travis_retry yarn test
  - travis_retry yarn build